--出荷伝票発行SQL
SELECT
  S1.DATA_CHAR
 ,S1.DATA_CHAR2
 ,S1.DATA_CHAR3
 ,S1.DATA_CHAR4
 ,S1.DATA_CHAR5
 ,S1.DATA_CHAR6
 ,SA.ORDER_RECV_DATE
 ,SA.ORDER_NO
 ,SA.CUST_ORDER_NO
 ,SS.SHIP_NO
 ,SH.CUST_DESC SHIP_DESC
 ,SA.ZIP_CD SHIP_ZIP
 ,SA.ADDRESS1 SHIP_ADD1
 ,SA.ADDRESS2 SHIP_ADD2
 ,SA.ADDRESS3 SHIP_ADD3
 ,SA.ADDRESS4 SHIP_ADD4
 ,SA.TELNO  SHIP_TEL
 ,SA.FAXNO SHIP_FAX
 ,SA.CUST_ATTN
 ,CM.CUST_DESC
 ,CM.ZIP_CD CUST_ZIP
 ,CM.ADDRESS1 CUST_ADD1
 ,CM.ADDRESS2 CUST_ADD2
 ,CM.ADDRESS3 CUST_ADD3
 ,CM.ADDRESS4 CUST_ADD4
 ,CM.TELNO CUST_TEL
 ,CM.FAXNO CUST_FAX
 ,SOD.ITEM_NO
 ,IM.ITEM_DESC
 ,SOD.SHIP_CNT
 ,SOD.ORDER_QTY
 ,SS.SCH_SHIP_QTY
 ,CASE ISNULL(S5.DATA_INT,0) WHEN 0 THEN  S4.DATA_INT ELSE S5.DATA_INT END LANG 
 ,SS.ALLOC_QTY 
FROM SHIPPING_SCHEDULE SS
INNER JOIN SALES_ORDER SA ON SA.ORDER_NO = SS.ORDER_NO
INNER JOIN SALES_ORDER_DETAIL SOD ON SOD.ORDER_NO = SS.ORDER_NO AND SS.ORDER_LINE_NO = SOD.ORDER_LINE_NO
LEFT OUTER JOIN CUSTOMER_MASTER CM ON SA.CUST_CD = CM.CUST_CD AND SA.CUST_SUB_CD = CM.CUST_SUB_CD
LEFT OUTER JOIN CUSTOMER_MASTER SH ON SA.SHIP_TO_CD = SH.CUST_CD AND SA.SHIP_TO_SUB_CD = SH.CUST_SUB_CD
LEFT OUTER JOIN ITEM_MASTER IM ON IM.ITEM_NO = SOD.ITEM_NO
LEFT OUTER JOIN SYSTEM_PARAMETER S1 ON S1.KEY01 = 'COMPANY_CD' AND S1.KEY02 = '*'
LEFT JOIN SYSTEM_PARAMETER S4 ON S4.KEY01 = 'PRINT_LANG' AND S4.KEY02 = '*'
LEFT JOIN SYSTEM_PARAMETER S5 ON S5.KEY01 = 'COUNTRY_CD' AND S5.KEY02 = CM.COUNTRY_CD
WHERE 1 = 1 
  AND SS.ORDER_STATUS < 90
  AND SS.SLIP_PRINT_FLAG = @SLIP_PRINT_FLAG
  AND SS.SHIP_NO =  @SHIP_NO
