 --受注一覧リストSQL
 SELECT
  SA.PO_TYPE
 ,SA.CUST_CD+'-'+SA.CUST_SUB_CD AS CUST_CD
 ,CU.CUST_NAME
 ,SA.SHIP_TO_CD+'-'+SA.SHIP_TO_SUB_CD AS SHIP_TO_CD
 ,CU1.CUST_NAME SHIP_TO_NAME
 ,SA.ORDER_RECV_DATE
 ,SA.ORDER_NO
 ,SA.CUST_ORDER_NO
 ,SAD.ITEM_NO
 ,I.ITEM_DESC
 ,COALESCE(S.DATA_CHAR, I.SCH_ID) AS SCH_ID
 ,SAD.ORDER_QTY
 ,SAD.ACTUAL_SHIP_QTY                 
 ,COALESCE(S2.DATA_CHAR, I.ITEM_UMSR) AS ITEM_UMSR
 ,SAD.UNIT_PRICE
 ,(SAD.UNIT_PRICE * SAD.ORDER_QTY) AS AllMoney  
 ,COALESCE(S3.DATA_CHAR, SAD.CURRENCY) AS CURRENCY
 ,SAD.DELIV_DATE
 ,SAD.SHIP_REQ_DATE
 ,SAD.JOC_CD
 ,SAD.SHIP_WHS
 ,W.WHS_DESC
 FROM SALES_ORDER SA
 LEFT JOIN SALES_ORDER_DETAIL SAD  ON  SA.ORDER_NO=SAD.ORDER_NO
 LEFT JOIN CUSTOMER_MASTER CU ON SA.CUST_CD=CU.CUST_CD AND SA.CUST_SUB_CD=CU.CUST_SUB_CD      
 LEFT JOIN CUSTOMER_MASTER CU1 ON SA.SHIP_TO_CD=CU1.CUST_CD AND SA.SHIP_TO_SUB_CD=CU1.CUST_SUB_CD
 LEFT JOIN ITEM_MASTER I ON SAD.ITEM_NO = I.ITEM_NO
 LEFT JOIN SYSTEM_PARAMETER  S ON S.KEY01='SCH_ID' AND S.KEY02=I.SCH_ID
 LEFT JOIN SYSTEM_PARAMETER S2 ON S2.KEY01='ITEM_UMSR' AND S2.KEY02=I.ITEM_UMSR
 LEFT JOIN SYSTEM_PARAMETER S3 ON S3.KEY01='CURRENCY_CD' AND  S3.KEY02=SAD.CURRENCY
 LEFT JOIN WAREHOUSE_MASTER W  ON SAD.SHIP_WHS=W.WHS_CD
 WHERE 1=1
   AND (SA.CUST_CD = @CUST_CD or @CUST_CD='')
   AND (SA.CUST_SUB_CD = @CUST_SUB_CD or @CUST_SUB_CD='' )
   AND (I.SCH_ID = @SCH_ID or @SCH_ID='')
   AND (SA.ORDER_RECV_DATE >= @BEG_ORDER_RECV_DATE or @BEG_ORDER_RECV_DATE=0)
   AND (SA.ORDER_RECV_DATE <= @END_ORDER_RECV_DATE or @END_ORDER_RECV_DATE=0)